[versions]
android-gradle-plugin = "8.7.3"
androidx-activity = "1.9.3"
androidx-appcompat = "1.7.0"
androidx-core = "1.15.0"
androidx-documentfile = "1.0.1"
androidx-fragment = "1.8.5"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.3.2"
jgit = "7.1.0.202411261347-r"
json = "20240303"
junit = "1.2.1"
kotlin = "2.1.0"
kotlinx-serialization = "1.7.3"
kudzu = "5.3.0"
material = "1.12.0"
google-gms-google-services = "4.4.2"
firebase-firestore = "25.1.1"
firebase-storage = "21.0.1"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidx-documentfile" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "androidx-preference" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kudzu = { group = "io.github.copper-leaf", name = "kudzu-core", version.ref = "kudzu" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Test
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }

# Build script
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
json = { group = "org.json", name = "json", version.ref = "json" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebase-firestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebase-storage" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "google-gms-google-services" }
